-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 15:59:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema agencja
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `agencja` ;

-- -----------------------------------------------------
-- Schema agencja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agencja` DEFAULT CHARACTER SET utf8 ;
USE `agencja` ;

-- -----------------------------------------------------
-- Table `agencja`.`klient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`klient` ;

CREATE TABLE IF NOT EXISTS `agencja`.`klient` (
  `klient__ID` INT(11) NOT NULL,
  `klient__imie` VARCHAR(45) NULL DEFAULT NULL,
  `klient__nazwisko` VARCHAR(100) NULL DEFAULT NULL,
  `klient__pesel` VARCHAR(11) NULL DEFAULT NULL,
  `klient__numertelefonu` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`klient__ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela zawierająca dane klientów';


-- -----------------------------------------------------
-- Table `agencja`.`dzwonienie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`dzwonienie` ;

CREATE TABLE IF NOT EXISTS `agencja`.`dzwonienie` (
  `dzwonienie__ID` INT(11) NOT NULL,
  `dzw__kiedyzadzwonic` DATETIME NULL DEFAULT NULL,
  `dzw__zadzwonione` TINYINT(4) NULL DEFAULT NULL,
  `klient_klient__ID` INT(11) NOT NULL,
  PRIMARY KEY (`dzwonienie__ID`),
  INDEX `fk_dzwonienie_klient1_idx` (`klient_klient__ID` ASC),
  CONSTRAINT `fk_dzwonienie_klient1`
    FOREIGN KEY (`klient_klient__ID`)
    REFERENCES `agencja`.`klient` (`klient__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela zawierająca dane o połączeniach z klientami.';


-- -----------------------------------------------------
-- Table `agencja`.`efekt_dzwonienia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`efekt_dzwonienia` ;

CREATE TABLE IF NOT EXISTS `agencja`.`efekt_dzwonienia` (
  `efekt_dzwonienia__ID` INT(11) NOT NULL AUTO_INCREMENT,
  `efekt_dzwonienia__opis` VARCHAR(255) NULL DEFAULT NULL,
  `dzwonienie_dzwonienie__ID` INT(11) NOT NULL,
  PRIMARY KEY (`efekt_dzwonienia__ID`),
  INDEX `fk_efekt_dzwonienia_dzwonienie1_idx` (`dzwonienie_dzwonienie__ID` ASC),
  CONSTRAINT `fk_efekt_dzwonienia_dzwonienie1`
    FOREIGN KEY (`dzwonienie_dzwonienie__ID`)
    REFERENCES `agencja`.`dzwonienie` (`dzwonienie__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela zawierająca dane o efektach połączeń z klientami.';

-- -----------------------------------------------------
-- Table `agencja`.`spotkanie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`spotkanie` ;

CREATE TABLE IF NOT EXISTS `agencja`.`spotkanie` (
  `spotkanie__ID` INT(11) NOT NULL,
  `spot__termin` DATETIME NULL DEFAULT NULL,
  `spot__przypomnienie_dni` INT(11) NULL DEFAULT NULL,
  `spot__przypomnienie_godz` INT(11) NULL DEFAULT NULL,
  `spot__przypomnienie_min` INT(11) NULL DEFAULT NULL,
  `spot__odbylo_sie` TINYINT(4) NULL DEFAULT NULL,
  `klient_klient__ID` INT(11) NOT NULL,
  PRIMARY KEY (`spotkanie__ID`),
  INDEX `fk_spotkanie_klient1_idx` (`klient_klient__ID` ASC),
  CONSTRAINT `fk_spotkanie_klient1`
    FOREIGN KEY (`klient_klient__ID`)
    REFERENCES `agencja`.`klient` (`klient__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela pomagająca umówić spotkania';


-- -----------------------------------------------------
-- Table `agencja`.`efekt_spotkania`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`efekt_spotkania` ;

CREATE TABLE IF NOT EXISTS `agencja`.`efekt_spotkania` (
  `efekt__ID` INT(11) NOT NULL,
  `efekt__opis` TEXT NULL DEFAULT NULL,
  `spotkanie_spotkanie__ID` INT(11) NOT NULL,
  PRIMARY KEY (`efekt__ID`),
  INDEX `fk_efekt_spotkania_spotkanie_idx` (`spotkanie_spotkanie__ID` ASC),
  CONSTRAINT `fk_efekt_spotkania_spotkanie`
    FOREIGN KEY (`spotkanie_spotkanie__ID`)
    REFERENCES `agencja`.`spotkanie` (`spotkanie__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela opisujaca efekt spotkania';


-- -----------------------------------------------------
-- Table `agencja`.`produkty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`produkty` ;

CREATE TABLE IF NOT EXISTS `agencja`.`produkty` (
  `produkty__ID` INT(11) NOT NULL,
  `prod__nazwa` VARCHAR(45) NULL DEFAULT NULL,
  `prod__opis` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`produkty__ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela produktów ubezpieczeniowych';


-- -----------------------------------------------------
-- Table `agencja`.`spotkania_miejsca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`spotkania_miejsca` ;

CREATE TABLE IF NOT EXISTS `agencja`.`spotkania_miejsca` (
  `spotkania_miejsca__ID` INT(11) NOT NULL,
  `spotkania_miejsca__nazwa_miejsca` VARCHAR(100) NULL DEFAULT NULL,
  `spotkania_miejsca__ulica` VARCHAR(45) NULL DEFAULT NULL,
  `spotkania_miejsca__nr_domu` VARCHAR(45) NULL DEFAULT NULL,
  `spotkania_miejsca__nr_lokalu` VARCHAR(45) NULL DEFAULT NULL,
  `spotkania_miejsca__miasto` VARCHAR(45) NULL DEFAULT NULL,
  `spotkania_miejsca__panstwo` VARCHAR(45) NULL DEFAULT NULL,
  `spotkania_miejsca__opis` BLOB NULL,
  PRIMARY KEY (`spotkania_miejsca__ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela zawierająca dane o miejscach spotkań z klientami.';


-- -----------------------------------------------------
-- Table `agencja`.`wniosek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`wniosek` ;

CREATE TABLE IF NOT EXISTS `agencja`.`wniosek` (
  `wniosek__ID` INT(11) NOT NULL AUTO_INCREMENT,
  `wniosek__numer_wniosku` VARCHAR(45) NULL DEFAULT NULL,
  `wniosek__stawka_uroczniona` VARCHAR(45) NULL DEFAULT NULL,
  `wniosek__czestotliwosc` VARCHAR(45) NULL DEFAULT NULL,
  `wniosek__czas_trwania` VARCHAR(45) NULL DEFAULT NULL,
  `produkty_produkty__ID` INT(11) NOT NULL,
  `klient_klient__ID` INT(11) NOT NULL,
  PRIMARY KEY (`wniosek__ID`),
  INDEX `fk_wniosek_produkty1_idx` (`produkty_produkty__ID` ASC),
  INDEX `fk_wniosek_klient1_idx` (`klient_klient__ID` ASC),
  CONSTRAINT `fk_wniosek_klient1`
    FOREIGN KEY (`klient_klient__ID`)
    REFERENCES `agencja`.`klient` (`klient__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wniosek_produkty1`
    FOREIGN KEY (`produkty_produkty__ID`)
    REFERENCES `agencja`.`produkty` (`produkty__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela zawierająca dane o podpisanych wnioskach z klientami.';


-- -----------------------------------------------------
-- Table `agencja`.`umowa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`umowa` ;

CREATE TABLE IF NOT EXISTS `agencja`.`umowa` (
  `umowa__ID` INT(11) NOT NULL AUTO_INCREMENT,
  `umowa__data_rozpoczecia` DATE NULL DEFAULT NULL,
  `wniosek_wniosek__ID` INT(11) NOT NULL,
  PRIMARY KEY (`umowa__ID`),
  INDEX `fk_umowa_wniosek1_idx` (`wniosek_wniosek__ID` ASC),
  CONSTRAINT `fk_umowa_wniosek1`
    FOREIGN KEY (`wniosek_wniosek__ID`)
    REFERENCES `agencja`.`wniosek` (`wniosek__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Tabela zawierająca dane o uruchomionych umowach z klientami.';


-- -----------------------------------------------------
-- Table `agencja`.`spotkanie_miejsce`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`spotkanie_miejsce` ;

CREATE TABLE IF NOT EXISTS `agencja`.`spotkanie_miejsce` (
  `spotkanie_miejsce__ID` INT NOT NULL AUTO_INCREMENT,
  `spotkania_miejsca_spotkanie_miejsce__ID` INT(11) NOT NULL,
  `spotkanie_spotkanie__ID` INT(11) NOT NULL,
  PRIMARY KEY (`spotkanie_miejsce__ID`),
  INDEX `fk_spotkanie_miejsce_spotkania_miejsca1_idx` (`spotkania_miejsca_spotkanie_miejsce__ID` ASC),
  INDEX `fk_spotkanie_miejsce_spotkanie2_idx` (`spotkanie_spotkanie__ID` ASC),
  CONSTRAINT `fk_spotkanie_miejsce_spotkania_miejsca1`
    FOREIGN KEY (`spotkania_miejsca_spotkanie_miejsce__ID`)
    REFERENCES `agencja`.`spotkania_miejsca` (`spotkania_miejsca__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_spotkanie_miejsce_spotkanie2`
    FOREIGN KEY (`spotkanie_spotkanie__ID`)
    REFERENCES `agencja`.`spotkanie` (`spotkanie__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela zawierająca dane o miejcach spotkań z konkretnymi z klientami.';


-- -----------------------------------------------------
-- Table `agencja`.`produkty_zaleznosc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencja`.`produkty_zaleznosc` ;

CREATE TABLE IF NOT EXISTS `agencja`.`produkty_zaleznosc` (
  `produkty_zaleznosc__ID` INT NOT NULL AUTO_INCREMENT,
  `produkty_zaleznosc__parent__ID` INT NULL,
  `produkty_produkty__ID` INT(11) NOT NULL,
  PRIMARY KEY (`produkty_zaleznosc__ID`),
  INDEX `fk_produkty_zaleznosc_produkty1_idx` (`produkty_produkty__ID` ASC),
  CONSTRAINT `fk_produkty_zaleznosc_produkty1`
    FOREIGN KEY (`produkty_produkty__ID`)
    REFERENCES `agencja`.`produkty` (`produkty__ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela zawierająca dane o zależnościach produktów ubezpieczeniowych.';

USE `agencja` ;

-- -----------------------------------------------------
-- Placeholder table for view `agencja`.`lista_dzwonienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencja`.`lista_dzwonienia` (
    `dzwonienie__ID` INT,
    `dzw__kiedyzadzwonic` INT,
    `dzw__zadzwonione` INT,
    `klient_klient__ID` INT,
    `klient__ID` INT,
    `klient__imie` INT,
    `klient__nazwisko` INT,
    `klient__pesel` INT,
    `klient__numertelefonu` INT
)
COMMENT = 'Tabela zawierająca dane o listach dzwonienia do klientów.';

-- -----------------------------------------------------
-- Placeholder table for view `agencja`.`lista_spotkan_z_klientami`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencja`.`lista_spotkan_z_klientami` (
    `spotkanie__ID` INT,
    `spot__termin` INT,
    `spot__przypomnienie_dni` INT,
    `spot__przypomnienie_godz` INT,
    `spot__przypomnienie_min` INT,
    `spot__odbylo_sie` INT,
    `klient_klient__ID` INT,
    `klient__ID` INT,
    `klient__imie` INT,
    `klient__nazwisko` INT,
    `klient__pesel` INT,
    `klient__numertelefonu` INT,
    `spotkanie_miejsce__ID` INT,
    `spotkanie_miejsce__nazwa_miejsca` INT,
    `spotkanie_miejsce__ulica` INT,
    `spotkanie_miejsce__nr_domu` INT,
    `spotkanie_miejsce__nr_lokalu` INT,
    `spotkanie_miejsce__miasto` INT,
    `spotkanie_miejsce__panstwo` INT,
    `spotkanie_spotkanie__ID` INT
)
COMMENT = 'Tabela zawierająca dane o połączeniach z klientami.';

-- -----------------------------------------------------
-- Placeholder table for view `agencja`.`wydzwonione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agencja`.`wydzwonione` (
    `dzwonienie__ID` INT,
    `dzw__kiedyzadzwonic` INT,
    `dzw__zadzwonione` INT,
    `klient_klient__ID` INT,
    `klient__ID` INT,
    `klient__imie` INT,
    `klient__nazwisko` INT,
    `klient__pesel` INT,
    `klient__numertelefonu` INT,
    `efekt_dzwonienia__ID` INT,
    `efekt_dzwonienia__opis` INT,
    `dzwonienie_dzwonienie__ID` INT
);

-- -----------------------------------------------------
-- View `agencja`.`lista_dzwonienia`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `agencja`.`lista_dzwonienia` ;
DROP TABLE IF EXISTS `agencja`.`lista_dzwonienia`;
USE `agencja`;
CREATE OR REPLACE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `agencja`.`lista_dzwonienia` AS
    SELECT 
        `agencja`.`dzwonienie`.`dzwonienie__ID` AS `dzwonienie__ID`,
        `agencja`.`dzwonienie`.`dzw__kiedyzadzwonic` AS `dzw__kiedyzadzwonic`,
        `agencja`.`dzwonienie`.`dzw__zadzwonione` AS `dzw__zadzwonione`,
        `agencja`.`dzwonienie`.`klient_klient__ID` AS `klient_klient__ID`,
        `agencja`.`klient`.`klient__ID` AS `klient__ID`,
        `agencja`.`klient`.`klient__imie` AS `klient__imie`,
        `agencja`.`klient`.`klient__nazwisko` AS `klient__nazwisko`,
        `agencja`.`klient`.`klient__pesel` AS `klient__pesel`,
        `agencja`.`klient`.`klient__numertelefonu` AS `klient__numertelefonu`
    FROM
        (`agencja`.`dzwonienie`
        JOIN `agencja`.`klient`)
    WHERE
        (`agencja`.`klient`.`klient__ID` = `agencja`.`dzwonienie`.`klient_klient__ID`);

-- -----------------------------------------------------
-- View `agencja`.`lista_spotkan_z_klientami`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `agencja`.`lista_spotkan_z_klientami` ;
DROP TABLE IF EXISTS `agencja`.`lista_spotkan_z_klientami`;
USE `agencja`;
CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `agencja`.`lista_spotkan_z_klientami` AS
    SELECT 
        `agencja`.`spotkanie`.`spotkanie__ID` AS `spotkanie__ID`,
        `agencja`.`spotkanie`.`spot__termin` AS `spot__termin`,
        `agencja`.`spotkanie`.`spot__przypomnienie_dni` AS `spot__przypomnienie_dni`,
        `agencja`.`spotkanie`.`spot__przypomnienie_godz` AS `spot__przypomnienie_godz`,
        `agencja`.`spotkanie`.`spot__przypomnienie_min` AS `spot__przypomnienie_min`,
        `agencja`.`spotkanie`.`spot__odbylo_sie` AS `spot__odbylo_sie`,
        `agencja`.`spotkanie`.`klient_klient__ID` AS `klient_klient__ID`,
        `agencja`.`klient`.`klient__ID` AS `klient__ID`,
        `agencja`.`klient`.`klient__imie` AS `klient__imie`,
        `agencja`.`klient`.`klient__nazwisko` AS `klient__nazwisko`,
        `agencja`.`klient`.`klient__pesel` AS `klient__pesel`,
        `agencja`.`klient`.`klient__numertelefonu` AS `klient__numertelefonu`,
        `agencja`.`spotkania_miejsca`.`spotkania_miejsca__ID` AS `spotkania_miejsca__ID`,
        `agencja`.`spotkania_miejsca`.`spotkania_miejsca__nazwa_miejsca` AS `spotkania_miejsca__nazwa_miejsca`,
        `agencja`.`spotkania_miejsca`.`spotkania_miejsca__ulica` AS `spotkania_miejsca__ulica`,
        `agencja`.`spotkania_miejsca`.`spotkania_miejsca__nr_domu` AS `spotkania_miejsca__nr_domu`,
        `agencja`.`spotkania_miejsca`.`spotkania_miejsca__nr_lokalu` AS `spotkania_miejsca__nr_lokalu`,
        `agencja`.`spotkania_miejsca`.`spotkania_miejsca__miasto` AS `spotkania_miejsca__miasto`,
        `agencja`.`spotkania_miejsca`.`spotkania_miejsca__panstwo` AS `spotkania_miejsca__panstwo`,
        `agencja`.`spotkanie_miejsce`.`spotkanie_miejsce__ID` AS `spotkanie_miejsce__ID`,
        `agencja`.`spotkanie_miejsce`.`spotkania_miejsca_spotkanie_miejsce__ID` AS `spotkania_miejsca_spotkanie_miejsce__ID`,
        `agencja`.`spotkanie_miejsce`.`spotkanie_spotkanie__ID` AS `spotkanie_miejsce__spotkanie_spotkanie__ID`
    FROM
        (((`agencja`.`spotkanie`
        JOIN `agencja`.`klient`)
        JOIN `agencja`.`spotkania_miejsca`)
        JOIN `agencja`.`spotkanie_miejsce`)
    WHERE
        ((`agencja`.`klient`.`klient__ID` = `agencja`.`spotkanie`.`klient_klient__ID`)
            AND (`agencja`.`spotkanie`.`spotkanie__ID` = `agencja`.`spotkanie_miejsce`.`spotkania_miejsca_spotkanie_miejsce__ID`)
            AND (`agencja`.`spotkanie_miejsce`.`spotkania_miejsca_spotkanie_miejsce__ID` = `agencja`.`spotkania_miejsca`.`spotkania_miejsca__ID`));


-- -----------------------------------------------------
-- View `agencja`.`wydzwonione`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `agencja`.`wydzwonione` ;
DROP TABLE IF EXISTS `agencja`.`wydzwonione`;
USE `agencja`;
CREATE OR REPLACE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `agencja`.`wydzwonione` AS
    SELECT 
        `agencja`.`dzwonienie`.`dzwonienie__ID` AS `dzwonienie__ID`,
        `agencja`.`dzwonienie`.`dzw__kiedyzadzwonic` AS `dzw__kiedyzadzwonic`,
        `agencja`.`dzwonienie`.`dzw__zadzwonione` AS `dzw__zadzwonione`,
        `agencja`.`dzwonienie`.`klient_klient__ID` AS `klient_klient__ID`,
        `agencja`.`klient`.`klient__ID` AS `klient__ID`,
        `agencja`.`klient`.`klient__imie` AS `klient__imie`,
        `agencja`.`klient`.`klient__nazwisko` AS `klient__nazwisko`,
        `agencja`.`klient`.`klient__pesel` AS `klient__pesel`,
        `agencja`.`klient`.`klient__numertelefonu` AS `klient__numertelefonu`,
        `agencja`.`efekt_dzwonienia`.`efekt_dzwonienia__ID` AS `efekt_dzwonienia__ID`,
        `agencja`.`efekt_dzwonienia`.`efekt_dzwonienia__opis` AS `efekt_dzwonienia__opis`,
        `agencja`.`efekt_dzwonienia`.`dzwonienie_dzwonienie__ID` AS `dzwonienie_dzwonienie__ID`
    FROM
        ((`agencja`.`dzwonienie`
        LEFT JOIN `agencja`.`klient` ON ((`agencja`.`klient`.`klient__ID` = `agencja`.`dzwonienie`.`klient_klient__ID`)))
        LEFT JOIN `agencja`.`efekt_dzwonienia` ON ((`agencja`.`efekt_dzwonienia`.`dzwonienie_dzwonienie__ID` = `agencja`.`dzwonienie`.`dzwonienie__ID`)))
    WHERE
        (`agencja`.`dzwonienie`.`dzw__zadzwonione` = 1);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
